version: '3.4'
networks:
  job-dev:
    driver: bridge
services:
  ewallet:
    image: ewallet:latest
    depends_on:
      - "Sqlite"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"

volumes:
  db_volume: